# Generated by Django 4.0.5 on 2022-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentgroup_students_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, choices=[('mel', 'мел'), ('bolt', 'болт')], max_length=100, null=True, verbose_name='Прізвище'),
        ),
    ]
